#!/bin/bash
set -euo pipefail
cd $(dirname $0)/../..

source ./aws-cli/set-env

display_status "Create table: ${TABLE_NAME}"
aws dynamodb create-table \
    --table-name ${TABLE_NAME} \
    --attribute-definitions \
        AttributeName=${HASH_KEY},AttributeType=S \
        AttributeName=${RANGE_KEY},AttributeType=S \
    --key-schema AttributeName=${HASH_KEY},KeyType=HASH AttributeName=${RANGE_KEY},KeyType=RANGE \
    --billing-mode PAY_PER_REQUEST  
 