#!/bin/bash
set -euo pipefail
cd $(dirname $0)/../..

source ./aws-cli/set-env

display_status "Create global GSI for table ${TABLE_NAME}  "
  
aws dynamodb update-table \
  --table-name ${TABLE_NAME} \
  --billing-mode PAY_PER_REQUEST \
  --attribute-definitions \
    AttributeName=memberName,AttributeType=S \
  --region ap-southeast-1 \
  --global-secondary-index-updates file://aws-cli/table/config/global-secondary-index.json
