#!/bin/bash
set -euo pipefail
cd $(dirname $0)/../..

source ./aws-cli/set-env

display_status "Update table: ${TABLE_NAME}"
aws dynamodb update-table \
    --table-name ${TABLE_NAME} \
    --billing-mode PAY_PER_REQUEST \
    --attribute-definitions \
      AttributeName=memberName,AttributeType=S \
      AttributeName=startDate,AttributeType=S 
 